
export const actionTypes = {
    COMPUTE_CURRENT_PREDICTION: 'COMPUTE_CURRENT_PREDICTION',
    RECOMPUTE_PREDICTIONS: 'RECOMPUTE_PREDICTIONS',
    RESTORE_PW: 'RESTORE_PW',
    CREATE_PW: 'CREATE_PW'
};
