
export const actionTypes = {
    INIT_APP: 'INIT_APP',
    COMPUTE_CURRENT_PREDICTION: 'COMPUTE_CURRENT_PREDICTION',
    RESET_CURRENT_PREDICTION: 'RESET_CURRENT_PREDICTION',
    RECOMPUTE_PREDICTIONS: 'RECOMPUTE_PREDICTIONS',
    PREPARE_TF_PREDICTION: 'PREPARE_TF_PREDICTION',
    REGISTER_USER: 'REGISTER_USER',
    RESTORE_PW: 'RESTORE_PW',
    CREATE_PW: 'CREATE_PW',
    LOG_OUT: 'LOG_OUT',
    LOG_IN: 'LOG_IN',
    SET_PREDICTIONS_FILER: 'SET_PREDICTIONS_FILER'
};
